name: you-get
on:
  push:
    branches:
      - 'main'
    paths:
      - 'you-get/**/*'
  schedule:
    - cron: '0 0 * * 3'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./you-get
          push: true
          tags: yandy0725/you-get:latest
